auth_enabled: false

ingester:
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  max_chunk_age: 1h
  chunk_encoding: snappy
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

server:
  http_listen_port: 3100
  log_level: info

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# Scrape configuration for logs
scrape_configs:
  # Docker logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_service_name']
        target_label: 'service'

  # API Gateway logs
  - job_name: api-gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-gateway
          __path__: /var/log/api-gateway/*.log

  # User Service logs
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /var/log/user-service/*.log

  # Market Data Service logs
  - job_name: market-data-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: market-data-service
          __path__: /var/log/market-data-service/*.log

  # Analytics Service logs
  - job_name: analytics-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics-service
          __path__: /var/log/analytics-service/*.log

  # Sentiment Service logs
  - job_name: sentiment-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: sentiment-service
          __path__: /var/log/sentiment-service/*.log

# Pipeline stages for parsing logs
pipeline_stages:
  - json:
      expressions:
        msg: message
        level: level
        ts: timestamp
        service: service_name
        request_id: request_id
  - labels:
      level:
      service:
      request_id:
